Protobuf definition for Optimint types
lazyledger/optimint pull request #57
Opened 2021-05-21 11:40 UTC by tzdybal

2021-05-25 13:21 UTC, liamsi requested changes
This should only contain the protobuf types that are necessary because either
1) they are core types in optimint or
2) they are necessary because of ABCI

2021-05-25 13:21 UTC, liamsi commented on proto/tendermint/consensus/types.proto
> +}
Does this go through the ABCI boundary? I don't think rounds are necessary in optimint.

2021-05-25 13:21 UTC, liamsi commented on proto/tendermint/consensus/types.proto
> +}
All these messages should not need to be part of optimint as they are tendermint consensus specific.

2021-05-25 13:21 UTC, liamsi commented on proto/tendermint/consensus/wal.proto
> +}
This is also tendermint specific.

2021-05-26 12:11 UTC, liamsi approved these changes
LGTM

2021-05-26 12:11 UTC, liamsi commented on proto/tendermint/abci/types.proto
> +}
We might want to change that to Aggregator. But we can think about this further and do this in a followup PR.

2021-05-26 13:56 UTC, tzdybal commented on da/lazyledger/lazyledger_test.go
> +	t.Skip("unfinished test/implementation")
This PR is targetting `tzdybal/payformessage` and the test is from that base branch. It's not working yet, and is under development there. It's not related to protobuf changes anyways.

2021-05-26 20:52 UTC, merged